### ISSUE TITLE
Blog Posts don't show

### ISSUE THREAD

**Issue by basicde** [jasonwebb/jasonwebb.io-theme#21]
Hi, doesn't appear to be pulling blog posts through even when the slug is correct, any ideas?

**Comment by jasonwebb** [comment]
1. Check that the posts are published, and not in draft.
2. Make sure that every post has the category 'work'.
3. Make sure that the "work" category slug is all lowercase ('work' not 'Work').
4. Check your DevTools console for errors, maybe that'll give a clue to any missing files or connection issues.
5. If you're not getting any console errors, start by debugging the [response returned from the ajax call in `entry.js`](https://github.com/jasonwebb/jasonwebb.io-theme/blob/main/js/entry.js#L329-L352).
6. If the ajax call is working, but just returning empty result sets, [look into `getItems.php`](https://github.com/jasonwebb/jasonwebb.io-theme/blob/main/php/getItems.php) to see if the `query_posts` call is being constructed and executed as you expect. Note that on [lines 64-65](https://github.com/jasonwebb/jasonwebb.io-theme/blob/main/php/getItems.php#L64-L65) you can return whatever you want as a response to the ajax calls, which you can use for debugging.
